### ISSUE TITLE
Add Empty

### ISSUE THREAD

**Issue by ratmice** [Crazytieguy/gat-lending-iterator#13]
I was considering writing a PR for empty, which is sometimes useful.
but it seemed like there was two ways that came to mind for implementing it.

1. using the to_lending approach, with something to the effect of `impl LendingIterator for std::iter::Empty<T>`,
2. providing it's own `gat_lending_iterator::Empty` type.

I thought 1. was probably the right approach but figured I would check first.

**Comment by Crazytieguy** [comment]
Thanks for writing 🙂

My current approach is to avoid any types being both an `Iterator` and a `LendingIterator`, since they have methods with the same names and the user would have to qualify which trait they want to use.

Also - I'm currently working on an update that will let you turn any `Iterator` into a `LendingIterator`, which would allow for example `std::iter::empty().into_lending()`, which I think is clean and reduces the amount of code that would be required in this crate.

Does that sound like a good solution to you?

**Comment by ratmice** [comment]
I hadn't considered that trait method overlap issue, the `into_lending()` solution sounds great. I will test out your latest patch with that tomorrow, but I think in light of that we can close this one.
